#  QUANTUMBLACK CONFIDENTIAL
#
#  Copyright (c) 2019 - present, QuantumBlack Visual Analytics Ltd. All
#  Rights Reserved.
#
#  NOTICE: All information contained herein is, and remains the property of
#  QuantumBlack Visual Analytics Ltd. and its suppliers, if any. The
#  intellectual and technical concepts contained herein are proprietary to
#  QuantumBlack Visual Analytics Ltd. and its suppliers and may be covered
#  by UK and Foreign Patents, patents in process, and are protected by trade
#  secret or copyright law. Dissemination of this information or
#  reproduction of this material is strictly forbidden unless prior written
#  permission is obtained from QuantumBlack Visual Analytics Ltd.

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: Install dependencies
          command: |
            poetry install
      - save_cache:
          paths:
            - ./venv
          key: deps-{{ checksum "poetry.lock" }}
      - run:
          name: Run code checks
          command: |
            . venv/bin/activate
            poetry run black src --check
      - run:
            name: Run tests
            command: |
              . venv/bin/activate
              poetry run coverage run --omit="/home/circleci/.cache/pypoetry/virtualenvs" -m pytest
              poetry run coveralls
