name: CI on poetry/black/tests

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        poetry-version: [1.1.2]
        os: [ubuntu-18.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run image
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - name: Load cache
      id: cached-poetry-dependencies
      uses: actions/cache@v2
      with:
        path: |
          /home/runner/.cache/pypoetry/virtualenvs
          /Users/runner/Library/Caches/pypoetry/virtualenvs
        key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
    - name: Install dependencies
      run: |
        poetry install --no-interaction
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
    - name: Black
      run: |
        poetry run black coding_the_matrix --check
    - name: pytest
      run: |
        poetry run pytest


